USE management;

CREATE TABLE User (
	u_id INT PRIMARY KEY AUTO_INCREMENT,
	u_name VARCHAR(64) NOT NULL,
	u_email VARCHAR(64) NOT NULL,
	u_password VARCHAR(64) NOT NULL,
	u_address VARCHAR(64) NOT NULL,
	u_phone VARCHAR(64) NOT NULL
) DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

CREATE TABLE Category (
	cg_id INT PRIMARY KEY AUTO_INCREMENT,
	cg_name VARCHAR(64)
) DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

CREATE TABLE Product (
	p_id INT PRIMARY KEY AUTO_INCREMENT,
	p_name VARCHAR(64) NOT NULL,
	p_description VARCHAR(64),
	p_image VARCHAR(1024),
	p_price INT NOT NULL,
	p_amount INT NOT NULL,
	p_cg_id INT NOT NULL,
	FOREIGN KEY(p_cg_id) REFERENCES Category(cg_id)
	ON DELETE CASCADE
	ON UPDATE CASCADE
) DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

CREATE TABLE Orders (
	o_id INT PRIMARY KEY AUTO_INCREMENT,
	o_amount INT NOT NULL,
	o_price INT NOT NULL,
	o_status INT NOT NULL,
	o_p_id INT NOT NULL,
	o_u_id INT NOT NULL,
	FOREIGN KEY(o_p_id) REFERENCES Product(p_id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(o_u_id) REFERENCES User(u_id) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

CREATE TABLE Cart (
	c_id INT PRIMARY KEY AUTO_INCREMENT,
	c_amount INT NOT NULL,
	c_log INT NOT NULL,
	c_price INT NOT NULL,
	c_u_id INT NOT NULL,
	c_p_id INT NOT NULL,
	FOREIGN KEY(c_p_id) REFERENCES Product(p_id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(c_u_id) REFERENCES User(u_id) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;